### ISSUE TITLE
Error with srct.DataStruct.ClusterError

### ISSUE THREAD

**Issue by Tylersuard** [purushottamkar/macer#4]
Command: python3 -m srcT.DataStruct.ClusterError

Error:
Traceback (most recent call last):
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/site-packages/clang/cindex.py", line 3925, in register_function
    func = getattr(lib, item[0])
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libclang.so: undefined symbol: clang_CXXConstructor_isConvertingConstructor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tyler/macer/srcT/DataStruct/ClusterError.py", line 4, in <module>
    from srcT.DataStruct.Code import Code
  File "/home/tyler/macer/srcT/DataStruct/Code.py", line 15, in <module>
    class Code:
  File "/home/tyler/macer/srcT/DataStruct/Code.py", line 17, in Code
    index = clang.cindex.Index.create()
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/site-packages/clang/cindex.py", line 2577, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/site-packages/clang/cindex.py", line 195, in __get__
    value = self.wrapped(instance)
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/site-packages/clang/cindex.py", line 4006, in lib
    register_functions(lib, not Config.compatibility_check)
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/site-packages/clang/cindex.py", line 3953, in register_functions
    register(f)
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/site-packages/clang/cindex.py", line 3950, in register
    return register_function(lib, item, ignore_errors)
  File "/home/tyler/anaconda3/envs/macer36/lib/python3.6/site-packages/clang/cindex.py", line 3931, in register_function
    raise LibclangError(msg)
clang.cindex.LibclangError: /usr/lib/x86_64-linux-gnu/libclang.so: undefined symbol: clang_CXXConstructor_isConvertingConstructor. Please ensure that your python bindings are compatible with your libclang.so version.

Linux Ubuntu 16
python 3.6
Anaconda

I uninstalled and re-installed Clang, still getting the same error.

**Comment by umairzahmed** [comment]
Hi, this typically occurs when your system Clang version (installed using `apt-get` or `make`) is incompatible with the Python-Clang binding version (installed via `pip3 install`). This error can be replicated by opening Python terminal (`$ python`), and importing clang (`import clang`)

Since this issue is independent of MACER, I would recommend searching online on how to fix it.
Sharing a related issue from another random GitHub project: https://github.com/JBakamovic/yavide/issues/78

**Comment by umairzahmed** [comment]
One suggestion is to uninstall the Python-Clang binding (`pip3 uninstall clang`) and reinstall it (`pip3 install clang`)

**Comment by Tylersuard** [comment]
Thank you, I really appreciate it!
